const PI=3.14159265;
const NW=33.4;  // molecules/nm³ in liquid water

// Cross sections (XE, XI, XC, XL, XSF*, XAE, XAC, XWE, XWS*) plus
// their log-space indexing constants (LOG_XE0, INV_LOG_XE_STEP, ...)
// are prepended to this shader at load time by fetching
// /cross_sections.wgsl (generated by tools/convert_g4data.py).
// DO NOT inline them here — edit the converter instead.

// Shell binding energies (eV) — G4DNAWaterIonisationStructure
const SB=array<f32,5>(10.79,13.39,16.05,32.30,539.0);
// Excitation energies (eV) — G4DNAEmfietzoglouWaterExcitationStructure
const EX=array<f32,5>(8.22,10.00,11.24,12.61,13.77);

fn xs_all(E:f32)->vec3<f32>{
  if(E<=XE[0]){return vec3<f32>(0.0,0.0,XL[0]);}
  if(E>=XE[XN-1u]){return vec3<f32>(XI[XN-1u],XC[XN-1u],XL[XN-1u]);}
  let t=(log(E)-LOG_XE0)*INV_LOG_XE_STEP;
  let i=u32(clamp(floor(t),0.0,f32(XN-2u)));
  let f=t-f32(i);
  let j=i+1u;
  return vec3<f32>(
    max(0.0,XI[i]+(XI[j]-XI[i])*f),
    max(0.0,XC[i]+(XC[j]-XC[i])*f),
    max(0.0,XL[i]+(XL[j]-XL[i])*f)
  );
}

fn xs_shell_fracs(E:f32)->array<f32,5>{
  if(E<=XE[0]){return array<f32,5>(XSF0[0],XSF1[0],XSF2[0],XSF3[0],XSF4[0]);}
  if(E>=XE[XN-1u]){return array<f32,5>(XSF0[XN-1u],XSF1[XN-1u],XSF2[XN-1u],XSF3[XN-1u],XSF4[XN-1u]);}
  let t=(log(E)-LOG_XE0)*INV_LOG_XE_STEP;
  let i=u32(clamp(floor(t),0.0,f32(XN-2u)));
  let f=t-f32(i);
  let j=i+1u;
  return array<f32,5>(
    max(0.0,XSF0[i]+(XSF0[j]-XSF0[i])*f),
    max(0.0,XSF1[i]+(XSF1[j]-XSF1[i])*f),
    max(0.0,XSF2[i]+(XSF2[j]-XSF2[i])*f),
    max(0.0,XSF3[i]+(XSF3[j]-XSF3[i])*f),
    max(0.0,XSF4[i]+(XSF4[j]-XSF4[i])*f)
  );
}

fn xs_exc_fracs(E:f32)->array<f32,5>{
  // XEF arrays have a data bug above ~8.6 keV (indices 86-99): all five levels
  // read 1.0 from the conversion script (division tiny/tiny = 1.0 when the
  // Emfietzoglou source data runs out of range). Detect that via sum > 1.0001
  // and fall back to the last valid index (i=85) so we keep physical branching.
  if(E<=XE[0]){return array<f32,5>(XEF0[0],XEF1[0],XEF2[0],XEF3[0],XEF4[0]);}
  if(E>=XE[XN-1u]){return array<f32,5>(XEF0[85],XEF1[85],XEF2[85],XEF3[85],XEF4[85]);}
  let t=(log(E)-LOG_XE0)*INV_LOG_XE_STEP;
  var i=u32(clamp(floor(t),0.0,f32(XN-2u)));
  // Clamp index to the last valid Emfietzoglou bin (85) to dodge the XEF bug.
  if(i>85u){i=85u;}
  let f=select(t-f32(i),0.0,i==85u);
  let j=min(i+1u,85u);
  let v0=max(0.0,XEF0[i]+(XEF0[j]-XEF0[i])*f);
  let v1=max(0.0,XEF1[i]+(XEF1[j]-XEF1[i])*f);
  let v2=max(0.0,XEF2[i]+(XEF2[j]-XEF2[i])*f);
  let v3=max(0.0,XEF3[i]+(XEF3[j]-XEF3[i])*f);
  let v4=max(0.0,XEF4[i]+(XEF4[j]-XEF4[i])*f);
  return array<f32,5>(v0,v1,v2,v3,v4);
}

fn xs_el_cos(E:f32,r:f32)->f32{
  let rr=clamp(r,0.0,1.0);
  let jf=rr*f32(N_AC-1u);
  let jlo=u32(floor(jf));
  let jhi=min(jlo+1u,N_AC-1u);
  let fj=jf-f32(jlo);
  let tE=(log(max(E,XAE[0]))-LOG_XAE0)*INV_LOG_XAE_STEP;
  let iE=u32(clamp(floor(tE),0.0,f32(N_AE-2u)));
  let fE=clamp(tE-f32(iE),0.0,1.0);
  let base0=iE*N_AC;
  let base1=(iE+1u)*N_AC;
  let c00=XAC[base0+jlo];let c01=XAC[base0+jhi];
  let c10=XAC[base1+jlo];let c11=XAC[base1+jhi];
  let cE0=c00+(c01-c00)*fj;
  let cE1=c10+(c11-c10)*fj;
  return clamp(cE0+(cE1-cE0)*fE,-1.0,1.0);
}

// Sample total energy transfer from Born differential ionization CDF.
// Uses paired CDF/E_transfer arrays with binary search (same algorithm as Geant4).
// Inputs: E_primary (eV), shell (0..4), r uniform in [0,1).
// Returns E_transfer (eV) = binding + secondary_KE.
fn sample_W_sec(E:f32,shell:u32,r:f32)->f32{
  // Find nearest primary energy in XWE via binary search
  // (XWE is NOT log-spaced — raw Born grid, linear below 30 eV)
  var lo:u32=0u;var hi:u32=N_WE-1u;
  while(hi-lo>1u){let mid=(lo+hi)/2u;if(XWE[mid]<=E){lo=mid;}else{hi=mid;}}
  let iE=select(lo,hi,abs(XWE[hi]-E)<abs(XWE[lo]-E)); // nearest
  let base=iE*N_WR;
  return bsearch_cdf(shell,base,r);
}
// Binary search in CDF array, return interpolated E_transfer.
fn bsearch_cdf(shell:u32,base:u32,r:f32)->f32{
  // Linear scan (N_WR=100, cheap; binary search saves ~50 iterations but
  // WGSL has no recursion and loop overhead is similar for N=100)
  var jlo:u32=0u;
  for(var j=0u;j<N_WR-1u;j++){
    let c=get_cdf(shell,base+j);
    if(c<=r){jlo=j;}else{break;}
  }
  let jhi=min(jlo+1u,N_WR-1u);
  let c0=get_cdf(shell,base+jlo);
  let c1=get_cdf(shell,base+jhi);
  let e0=get_etransfer(shell,base+jlo);
  let e1=get_etransfer(shell,base+jhi);
  if(c1<=c0){return e0;}
  let f=clamp((r-c0)/(c1-c0),0.0,1.0);
  // Linear interpolation (matches Geant4 G4DNACrossSectionDataSet log-log
  // on the raw data; our paired CDF breakpoints are already on the raw grid
  // so linear between breakpoints = same as np.interp on raw data)
  return e0+(e1-e0)*f;
}
fn get_cdf(shell:u32,idx:u32)->f32{
  if(shell==0u){return XWC0[idx];}
  if(shell==1u){return XWC1[idx];}
  if(shell==2u){return XWC2[idx];}
  if(shell==3u){return XWC3[idx];}
  return XWC4[idx];
}
fn get_etransfer(shell:u32,idx:u32)->f32{
  if(shell==0u){return XWT0[idx];}
  if(shell==1u){return XWT1[idx];}
  if(shell==2u){return XWT2[idx];}
  if(shell==3u){return XWT3[idx];}
  return XWT4[idx];
}

// Total Sanche vibrational cross section. Valid in 2-100 eV, zero outside.
// XVE is NOT log-spaced so we do a linear scan (N_VIB ~ 38, cheap).
fn xs_vib_total(E:f32)->f32{
  if(E<2.0||E>100.0){return 0.0;}
  for(var i=0u;i<N_VIB-1u;i++){
    if(E>=XVE[i]&&E<XVE[i+1u]){
      let f=(E-XVE[i])/(XVE[i+1u]-XVE[i]);
      return max(0.0,XVS[i]+(XVS[i+1u]-XVS[i])*f);
    }
  }
  return 0.0;
}

// Sample a vibrational mode (0..8) at energy E given uniform r in [0,1).
// Modes with threshold > E are disallowed.
fn sample_vib_mode(E:f32,r:f32)->u32{
  // Find bin i
  var bin:u32=0u;
  for(var i=0u;i<N_VIB-1u;i++){
    if(E>=XVE[i]&&E<XVE[i+1u]){bin=i;break;}
  }
  // Use the lower bin's fractions (no cross-bin interp needed — fine resolution)
  let base=bin*9u;
  // Build cumulative weighted CDF, respecting per-mode threshold (mode cannot fire if VIB_LEV[k] > E)
  var cumsum:f32=0.0;
  var cs:array<f32,9>;
  for(var k=0u;k<9u;k++){
    let frac=select(XVMF[base+k],0.0,VIB_LEV[k]>E);
    cumsum=cumsum+frac;
    cs[k]=cumsum;
  }
  if(cumsum<=0.0){return 0u;}
  let thr=r*cumsum;
  for(var k=0u;k<9u;k++){
    if(thr<cs[k]){return k;}
  }
  return 8u;
}

// Melton dissociative electron attachment: e⁻ + H₂O → OH⁻ + H (4–13 eV)
// Data: G4EMLOW sigma_attachment_e_melton.dat, converted 1e-18 cm² → nm²
const DEA_N = 14u;
const DEA_E = array<f32,14>(0.0, 4.2, 4.3, 5.8, 6.0, 6.2, 6.4, 7.0, 7.5, 7.7, 8.4, 10.2, 11.2, 12.3);
const DEA_S = array<f32,14>(0.0, 0.0, 0.0, 2.5e-5, 2.8e-4, 6.0e-4, 6.7e-4, 3.7e-4, 1.09e-4, 7.0e-5, 1.4e-4, 2.0e-5, 6.0e-5, 0.0);
fn xs_dea(E:f32)->f32{
  if(E<4.0||E>13.0){return 0.0;}
  for(var i=0u;i<DEA_N-1u;i++){
    if(E>=DEA_E[i]&&E<DEA_E[i+1u]){
      let f=(E-DEA_E[i])/(DEA_E[i+1u]-DEA_E[i]);
      return max(0.0,DEA_S[i]+(DEA_S[i+1u]-DEA_S[i])*f);
    }
  }
  return 0.0;
}

fn rl(x:u32,k:u32)->u32{return(x<<k)|(x>>(32u-k));}
fn rn(s:ptr<function,vec4u>)->u32{let r=rl((*s).x+(*s).w,7u)+(*s).x;let t=(*s).y<<9u;(*s).z^=(*s).x;(*s).w^=(*s).y;(*s).y^=(*s).z;(*s).x^=(*s).w;(*s).z^=t;(*s).w=rl((*s).w,11u);return r;}
fn rf(s:ptr<function,vec4u>)->f32{return f32(rn(s)>>1u)/2147483647.0;}
